In [2]:
%load_ext rpy2.ipython
!git clone "https://github.com/act-prma/AAR"

/usr/local/lib/python3.6/dist-packages/rpy2/robjects/pandas2ri.py:14: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
/usr/local/lib/python3.6/dist-packages/rpy2/robjects/pandas2ri.py:34: UserWarning: pandas >= 1.0 is not supported.
  warnings.warn('pandas >= 1.0 is not supported.')


Cloning into 'AAR'...


# 1. ¿Cuál es el resultado de la siguiente expresión?

a) 2 * 2.5

b) 9%%2

In [3]:
%%R
print("inciso a")
print(2*2.5)
print("inciso b")
print(9%%2)

[1] "inciso a"
[1] 5
[1] "inciso b"
[1] 1


#2.	Las edades de un grupo de amigos son 27, 23, 29, 24 y 31 años. Crea un vector de edades con estos datos y calcula su media, de forma que la salida se guarde en un fichero llamado amigos. Vuelve a calcularla, pero de manera que ahora el resultado salga por pantalla.


In [4]:
%%R
amigos <- c(27, 23, 29, 24, 31)
print(amigos)

[1] 27 23 29 24 31


#3.	Define el vector y = (1,3,5,7) utilizando la función c(). ¿Cómo lo harías con la función seq()?.

In [5]:
%%R
y <- seq(to=7, by=2)
print(y)

[1] 1 3 5 7


#4.Sabemos que para sumar vectores estos deben tener la misma longitud. Sin embargo, R trabaja de manera distinta. Define los vectores x = (1,2,3,4,5,6), y = (7,8), z = (9,10,11,12). Calcula:
a) x + x 

b) x + y. ¿Qué ha hecho R? 

c) x+z. Ahora R da un warning pero aun así nos da un resultado. ¿Cómo lo ha calculado?

In [6]:
%%R
x <- c(1:6)
y <- c(7,8)
z <- c(9:12)
print(x+x)
print(x+y)
print(x+z)

[1]  2  4  6  8 10 12
[1]  8 10 10 12 12 14
[1] 10 12 14 16 14 16


Para el inciso b) al ser X un vector de 6 entradas y Y de 2 entradas, se suman entrada por entrada del tamaño del vector mas grande, i.e., el vector más grande le suman el vector mas chico cuantas entradas tenga el grande.

Para el iniciso c), al igual que en el inciso b) se suman entrada por entrada, aún no siendo del mismo tamaño el vector, reiniciando en su primer entrada el vector mas chico cuando el otro es mas grande.

#5.	Se definió el vector x = (1,2,3,4,5,6). A partir de dicho vector se han construido las matrices m1, m2, m3, m4.



#Todas las matrices se han definido a partir de matrix(x,...). Reproduce el código necesario para obtener cada una de ellas.

In [7]:
%%R
x = c(1:6)
m1 = matrix(x, nrow=2, ncol=3)
m2 = matrix(x, nrow=3, ncol=2)
m3 = matrix(x, nrow=2, ncol=3, byrow=TRUE)
m4 = matrix(x, nrow=3, ncol=3, byrow=FALSE)
print(m1)
print(m2)
print(m3)
print(m4)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
     [,1] [,2] [,3]
[1,]    1    4    1
[2,]    2    5    2
[3,]    3    6    3


#6.	¿Cuál es la diferencia entre *, %*% y outer() ? Compruébalo con las matrices

In [8]:
%%R
A = matrix(c(2,1,3,4), nrow=2, ncol=2)
B = matrix(c(3,8))
print(A)
print(B)
#print(A*B) #Dejamos comentada esta por el hecho de que marca un error
            #por no ser un escalar
print(A%*%B)
print(outer(A,B))

     [,1] [,2]
[1,]    2    3
[2,]    1    4
     [,1]
[1,]    3
[2,]    8
     [,1]
[1,]   30
[2,]   35
, , 1, 1

     [,1] [,2]
[1,]    6    9
[2,]    3   12

, , 2, 1

     [,1] [,2]
[1,]   16   24
[2,]    8   32



La operacion "*" es para multiplicar las matrices por escalares, en cuanto a "%*%" es para hacer la multiplicacion de matrices y por ultimo "outer()" multiplica e imprime la primer matriz por cada uno de las entradas de la segunda matriz como si fuera un escalar. 

#7.	Un grupo de amigos está formado por Ana de 23 años, Luis de 24 años, Pedro de 22, Juan de 24, Eva de 21 y Jorge de 22 años. Crea los vectores correspondientes a nombre, edad y sexo. (Usa la codificacio´n M=mujer, H=hombre).
a)	Convierte el vector sexo en un factor sexf. ¿Cuáles son los niveles de dicho factor?

b)	Con los datos anteriores hemos creado el dataframe amigos. El resultado es:
¿Cuál es el código de R da como resultado esta salida?

c)	¿Cuál es la edad media de las chicas del grupo? ¿Y la de los chicos? Intenta responder a ambas preguntas con un único comando.

In [9]:
%%R
nombre = c("Ana", "Luis", "Pedro", "Eva")
edad = c(23, 24, 22, 21)
sexo = c("M", "H", "H", "M")
#Inciso a
sexf = factor(sexo)
print(sexf)
#Inciso b
amigos = data.frame(nombre, edad, sexo)
print(amigos)
#Inciso c
print(mean(amigos[,2]))

[1] M H H M
Levels: H M
  nombre edad sexo
1    Ana   23    M
2   Luis   24    H
3  Pedro   22    H
4    Eva   21    M
[1] 22.5


#8.	Escribe una función que calcule el factorial de un número. Recuerda que la factorial esta definido para valores enteros no negativos como: n! = n·(n−1)·...·2·1. La función debe dar mensaje de error en caso de introducir un valor que no sea entero o negativo.

In [25]:
%%R
factorial <- function(n){
  factorial <- 1
  if (n < 0){
    print("El numero no es valido, solo se aceptan positivos")
  }
  else{
    for (i in 1:n){
      factorial <- factorial * i
    }
    return(factorial)
  }
}

factorial(3)

[1] 6


#9. Escribe una función edades que, dado el día mes y año del nacimiento de una persona, nos devuelva la edad que tiene en el momento de la ejecución de la función.

In [54]:
%%R

edad <- function(nac){
  hoy <- Sys.Date()
  nac <- as.Date(as.integer(nac)) 
  #nac <- as.Date("1998-03-31")
  return(hoy - nac)
}
edad()

R[write to console]: Error in as.Date.numeric(as.integer(nac)) : 'origin' must be supplied
Calls: <Anonymous> ... <Anonymous> -> withVisible -> edad -> as.Date -> as.Date.numeric




Error in as.Date.numeric(as.integer(nac)) : 'origin' must be supplied
Calls: <Anonymous> ... <Anonymous> -> withVisible -> edad -> as.Date -> as.Date.numeric


In [0]:
 vhoy <- Sys.Date()
 vagniohoy <- format(vhoy, "%Y")
 vagniohoy <- as.numeric(vagniohoy)
 vhoy